name: sample only
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      ["main"]
  workflow_dispatch:

jobs:
  first-job:
    runs-on: ubuntu-latest
    on:
      pull_request:
        path:
          "./scr/main/java/service/DemoServiceImpl.java"
    steps:
      - name: first-job first STEP
        run: echo "First job first step"
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: NO job
        run: echo "NO JOB HERE"

